/* ==========================================================================
   PETROLHEAD TECHNICA — engine explorer catalogue
   --------------------------------------------------------------------------
   One manifest per car. Rendering logic lives in engine-viewer.js; everything
   car-specific lives here: geometry layout, semantic components, authored
   explosion paths, camera presets, bilingual copy and sources.

   Rules this file follows:
   · Only specifications that the cited source supports are listed in `facts`.
     Where a figure is not confirmed for our car it is simply absent.
   · `componentCount` is the number of semantic inspectable assemblies below —
     not triangles, not meshes, and not an engineering part total.
   · Explosion offsets are authored per assembly, in metres, in the engine's
     own space. They are directions that explain the machine, not a service
     removal order.
   ========================================================================== */

/** Shared category labels. */
export const CATEGORIES = {
  structure: { en: 'Engine structure', bm: 'Struktur enjin' },
  valve:     { en: 'Valvetrain',       bm: 'Rangkaian injap' },
  rotating:  { en: 'Rotating assembly', bm: 'Pemasangan berputar' },
  air:       { en: 'Air path',         bm: 'Laluan udara' },
  cooling:   { en: 'Cooling',          bm: 'Penyejukan' },
  ancillary: { en: 'Ancillaries',      bm: 'Kelengkapan sokongan' },
  electrical:{ en: 'Electrical',       bm: 'Elektrik' },
};

/* Components shared in shape between the two inline-fours. `over` lets a car
   override any field, so the N20 and the EA888 stay distinguishable. */
function inline4Components(over = {}) {
  const base = [
    {
      id: 'acoustic-cover', cat: 'structure',
      en: { name: 'Acoustic engine cover', summary: 'The moulded lid you actually see when the bonnet is up.',
        does: 'Damps injector and valvetrain noise and tidies the top of the engine. It is trim, not a structural part.',
        connects: 'Clips or bolts onto studs on the camshaft cover.', parts: ['Moulded cover', 'Isolating grommets', 'Retaining studs'] },
      bm: { name: 'Penutup akustik enjin', summary: 'Penutup acuan yang kelihatan sebaik bonet dibuka.',
        does: 'Meredam bunyi penyuntik dan rangkaian injap serta mengemaskan bahagian atas enjin. Ia hiasan, bukan bahagian struktur.',
        connects: 'Terpasang pada stad di penutup aci sesondol.', parts: ['Penutup acuan', 'Gromet pengasing', 'Stad penahan'] },
      offset: [0, 0.34, 0.03],
    },
    {
      id: 'cam-cover', cat: 'structure',
      en: { name: 'Camshaft cover', summary: 'Seals the top of the cylinder head.',
        does: 'Keeps oil inside the head and carries the oil filler and the crankcase breather path.',
        connects: 'Bolts to the top face of the cylinder head on a moulded gasket.', parts: ['Cover', 'Gasket set', 'Oil filler cap'] },
      bm: { name: 'Penutup aci sesondol', summary: 'Menutup bahagian atas kepala silinder.',
        does: 'Menahan minyak di dalam kepala serta membawa penutup pengisi minyak dan laluan nafas kotak engkol.',
        connects: 'Diskru pada permukaan atas kepala silinder dengan gasket acuan.', parts: ['Penutup', 'Set gasket', 'Penutup pengisi minyak'] },
      offset: [0, 0.24, 0.01],
    },
    {
      id: 'valvetrain', cat: 'valve',
      en: { name: 'Camshafts and valvetrain', summary: 'Opens and closes the valves in time with the crankshaft.',
        does: 'Two overhead camshafts run at half crankshaft speed. Their lobes push on the followers that open the intake and exhaust valves.',
        connects: 'Sits in the head on cam caps and is driven from the crankshaft by the timing chain.', parts: ['Intake camshaft', 'Exhaust camshaft', 'Cam caps', 'Followers'] },
      bm: { name: 'Aci sesondol dan rangkaian injap', summary: 'Membuka dan menutup injap seiring aci engkol.',
        does: 'Dua aci sesondol atas berputar pada separuh kelajuan aci engkol. Bonggolnya menolak pengikut yang membuka injap masuk dan ekzos.',
        connects: 'Duduk dalam kepala di atas tutup sesondol dan dipacu dari aci engkol oleh rantai pemasaan.', parts: ['Aci sesondol masuk', 'Aci sesondol ekzos', 'Tutup sesondol', 'Pengikut'] },
      offset: [0, 0.17, 0],
    },
    {
      id: 'cylinder-head', cat: 'structure',
      en: { name: 'Cylinder head', summary: 'The lid of the combustion chambers, and the house of the valves.',
        does: 'Forms the top of each combustion chamber and carries the intake and exhaust ports, the valve seats, the injectors and the spark plugs.',
        connects: 'Bolts down onto the block through the head gasket; manifolds bolt to its two side faces.', parts: ['Head casting', 'Valve seats and guides', 'Spark plug tubes'] },
      bm: { name: 'Kepala silinder', summary: 'Penutup kebuk pembakaran dan rumah kepada injap.',
        does: 'Membentuk bahagian atas setiap kebuk pembakaran serta membawa liang masuk dan ekzos, tempat duduk injap, penyuntik dan palam pencucuh.',
        connects: 'Diskru ke blok melalui gasket kepala; manifold dipasang pada dua permukaan sisinya.', parts: ['Tuangan kepala', 'Tempat duduk dan pemandu injap', 'Tiub palam pencucuh'] },
      offset: [0, 0.1, 0],
    },
    {
      id: 'head-gasket', cat: 'structure',
      en: { name: 'Head gasket', summary: 'The seal between head and block.',
        does: 'Holds combustion pressure in each bore while keeping the coolant and oil galleries separate as they cross the joint.',
        connects: 'Clamped between the block deck and the cylinder head by the head bolts.', parts: ['Multi-layer steel gasket'] },
      bm: { name: 'Gasket kepala', summary: 'Pengedap antara kepala dan blok.',
        does: 'Menahan tekanan pembakaran dalam setiap gerek sambil mengasingkan laluan penyejuk dan minyak yang melintasi sambungan itu.',
        connects: 'Diapit antara dek blok dan kepala silinder oleh bolt kepala.', parts: ['Gasket keluli berlapis'] },
      offset: [0, 0.055, 0],
    },
    {
      id: 'cylinder-block', cat: 'structure',
      en: { name: 'Cylinder block', summary: 'The main casting everything else hangs from.',
        does: 'Holds the four bores the pistons run in, carries the crankshaft main bearings underneath, and routes coolant and oil through its internal galleries.',
        connects: 'Head on top, sump beneath, gearbox on the bellhousing face, ancillaries on the side.', parts: ['Block casting', 'Cylinder liners', 'Main bearing caps', 'Core plugs'] },
      bm: { name: 'Blok silinder', summary: 'Tuangan utama tempat segalanya bergantung.',
        does: 'Memegang empat gerek tempat omboh bergerak, membawa galas utama aci engkol di bawahnya, dan menyalurkan penyejuk serta minyak melalui laluan dalamannya.',
        connects: 'Kepala di atas, sampan di bawah, kotak gear pada muka bellhousing, kelengkapan di sisi.', parts: ['Tuangan blok', 'Pelapik silinder', 'Tutup galas utama', 'Palam teras'] },
      offset: [0, 0, 0],
    },
    {
      id: 'crank-assembly', cat: 'rotating',
      en: { name: 'Crankshaft, rods and pistons', summary: 'Turns the push of combustion into rotation.',
        does: 'Each piston is driven down the bore by the burning charge and pushes its connecting rod against an offset crank journal, so straight-line movement becomes torque at the crank nose.',
        connects: 'Runs in the main bearings in the block; the flywheel and gearbox take the output.', parts: ['Crankshaft', 'Connecting rods', 'Pistons and rings', 'Bearing shells'] },
      bm: { name: 'Aci engkol, rod dan omboh', summary: 'Menukar tolakan pembakaran kepada putaran.',
        does: 'Setiap omboh ditolak ke bawah gerek oleh cas yang terbakar dan menolak rod penyambungnya pada jurnal engkol yang terpesong, menjadikan gerakan lurus sebagai tork di hidung engkol.',
        connects: 'Berputar dalam galas utama di dalam blok; roda tenaga dan kotak gear mengambil keluarannya.', parts: ['Aci engkol', 'Rod penyambung', 'Omboh dan gelang', 'Kulit galas'] },
      offset: [0, -0.06, 0.26],
    },
    {
      id: 'oil-sump', cat: 'structure',
      en: { name: 'Oil pan / sump', summary: 'The engine oil’s collection point.',
        does: 'Catches oil draining back from the head and block and holds the reservoir the oil pump draws from.',
        connects: 'Bolts to the underside of the block on a sealing bead; the drain plug sits at its lowest corner.', parts: ['Pan', 'Drain plug and washer', 'Pick-up and strainer'] },
      bm: { name: 'Sampan minyak', summary: 'Tempat minyak enjin berkumpul.',
        does: 'Menadah minyak yang mengalir balik dari kepala dan blok serta menyimpan takungan yang disedut oleh pam minyak.',
        connects: 'Diskru ke bawah blok pada manik pengedap; palam buang berada di sudut terendahnya.', parts: ['Sampan', 'Palam buang dan sesendal', 'Penyedut dan penapis'] },
      offset: [0, -0.3, 0],
    },
    {
      id: 'timing-case', cat: 'valve',
      en: { name: 'Timing drive and cover', summary: 'Keeps the camshafts in step with the crankshaft.',
        does: 'A chain from the crank nose drives both camshaft sprockets through a tensioned run, so valve events stay locked to piston position.',
        connects: 'Runs inside the cover on the end face of the block and head.', parts: ['Chain', 'Sprockets', 'Tensioner and guides', 'Cover'] },
      bm: { name: 'Pemacu dan penutup pemasaan', summary: 'Mengekalkan aci sesondol seiring aci engkol.',
        does: 'Rantai dari hidung engkol memacu kedua-dua sproket aci sesondol melalui laluan bertegang, supaya peristiwa injap kekal terkunci pada kedudukan omboh.',
        connects: 'Berjalan di dalam penutup pada muka hujung blok dan kepala.', parts: ['Rantai', 'Sproket', 'Penegang dan pemandu', 'Penutup'] },
      offset: [-0.3, 0.04, 0],
    },
    {
      id: 'intake-manifold', cat: 'air',
      en: { name: 'Intake manifold', summary: 'Shares incoming air between the four cylinders.',
        does: 'The plenum steadies the airflow behind the throttle and the runners carry equal shares of it to each intake port.',
        connects: 'Bolts to the intake face of the head; the throttle body sits at the plenum inlet.', parts: ['Plenum', 'Runners', 'Throttle body', 'Gaskets'] },
      bm: { name: 'Manifold masuk', summary: 'Mengagihkan udara masuk kepada empat silinder.',
        does: 'Plenum menstabilkan aliran udara di belakang pendikit dan salurannya membawa bahagian sama rata ke setiap liang masuk.',
        connects: 'Diskru pada muka masuk kepala; badan pendikit berada di muncung plenum.', parts: ['Plenum', 'Saluran', 'Badan pendikit', 'Gasket'] },
      offset: [0, 0.12, 0.34],
    },
    {
      id: 'exhaust-manifold', cat: 'air',
      en: { name: 'Exhaust manifold', summary: 'Collects the burnt gas from all four cylinders.',
        does: 'Gathers each exhaust port into a common outlet and feeds the turbine.',
        connects: 'Bolts to the exhaust face of the head; its outlet carries the turbocharger.', parts: ['Runners', 'Collector', 'Flange and studs'] },
      bm: { name: 'Manifold ekzos', summary: 'Mengumpul gas terbakar daripada keempat-empat silinder.',
        does: 'Menghimpunkan setiap liang ekzos ke satu muncung sepunya dan menyuap turbin.',
        connects: 'Diskru pada muka ekzos kepala; muncungnya membawa pengecas turbo.', parts: ['Saluran', 'Pengumpul', 'Bebibir dan stad'] },
      offset: [0, 0.1, -0.34],
    },
    {
      id: 'turbocharger', cat: 'air',
      en: { name: 'Turbocharger', summary: 'Uses exhaust energy to push more air in.',
        does: 'Exhaust gas spins the turbine wheel; the compressor wheel on the same shaft pressurises the intake air, so a given cylinder swallows a denser charge.',
        connects: 'Mounted on the exhaust manifold outlet, oil-fed from the block, compressor outlet piped to the charge cooler.', parts: ['Turbine housing', 'Compressor housing', 'Centre housing', 'Wastegate actuator', 'Oil feed and drain'] },
      bm: { name: 'Pengecas turbo', summary: 'Menggunakan tenaga ekzos untuk menolak lebih banyak udara masuk.',
        does: 'Gas ekzos memutarkan roda turbin; roda pemampat pada aci yang sama menekan udara masuk, jadi silinder menelan cas yang lebih tumpat.',
        connects: 'Dipasang pada muncung manifold ekzos, disuap minyak dari blok, keluaran pemampat berpaip ke penyejuk cas.', parts: ['Rumah turbin', 'Rumah pemampat', 'Rumah tengah', 'Penggerak gerbang buang', 'Suapan dan saliran minyak'] },
      offset: [0.08, 0.14, -0.42],
    },
    {
      id: 'cooling-pack', cat: 'cooling',
      en: { name: 'Cooling pack', summary: 'Vehicle-mounted heat exchangers, not part of the engine casting.',
        does: 'The radiator sheds heat the coolant has picked up from the block and head; the charge cooler drops the temperature of the air leaving the turbo compressor.',
        connects: 'Carried on the body structure ahead of the engine and joined to it only by hoses and pipework.', parts: ['Radiator core and tanks', 'Charge cooler', 'Mounting brackets'] },
      bm: { name: 'Pek penyejukan', summary: 'Penukar haba pada kenderaan, bukan sebahagian tuangan enjin.',
        does: 'Radiator melepaskan haba yang diambil penyejuk dari blok dan kepala; penyejuk cas menurunkan suhu udara yang keluar dari pemampat turbo.',
        connects: 'Dipikul pada struktur badan di hadapan enjin dan hanya disambung kepadanya oleh hos dan paip.', parts: ['Teras dan tangki radiator', 'Penyejuk cas', 'Pendakap pemasangan'] },
      offset: [0.42, 0.06, 0.34],
    },
    {
      id: 'coolant-hoses', cat: 'cooling',
      en: { name: 'Coolant hoses', summary: 'The flexible run between engine and radiator.',
        does: 'Carries hot coolant out of the head to the radiator and cooled coolant back into the block, while absorbing engine movement on its mounts.',
        connects: 'Clamped to the thermostat housing, the radiator tanks and the heater take-off.', parts: ['Upper hose', 'Lower hose', 'Heater hoses', 'Spring and worm clamps'] },
      bm: { name: 'Hos penyejuk', summary: 'Laluan fleksibel antara enjin dan radiator.',
        does: 'Membawa penyejuk panas keluar dari kepala ke radiator dan penyejuk sejuk kembali ke blok, sambil menyerap pergerakan enjin pada dudukannya.',
        connects: 'Diapit pada rumah termostat, tangki radiator dan cabang pemanas.', parts: ['Hos atas', 'Hos bawah', 'Hos pemanas', 'Pengapit spring dan ulir'] },
      offset: [0.26, 0.04, 0.24],
    },
    {
      id: 'belt-drive', cat: 'ancillary',
      en: { name: 'Accessory belt drive', summary: 'Takes power off the crank nose for the ancillaries.',
        does: 'One ribbed belt from the crankshaft pulley turns the alternator and the air-conditioning compressor, held in tension by a sprung tensioner.',
        connects: 'Wraps the crank pulley and each accessory pulley on the belt end of the engine.', parts: ['Ribbed belt', 'Crank pulley', 'Alternator', 'A/C compressor', 'Tensioner'] },
      bm: { name: 'Pemacu tali sawat', summary: 'Mengambil kuasa dari hidung engkol untuk kelengkapan.',
        does: 'Satu tali sawat berusuk dari takal aci engkol memutarkan alternator dan pemampat penyaman udara, ditegangkan oleh penegang berspring.',
        connects: 'Melilit takal engkol dan setiap takal kelengkapan di hujung tali sawat enjin.', parts: ['Tali sawat berusuk', 'Takal engkol', 'Alternator', 'Pemampat A/C', 'Penegang'] },
      offset: [-0.38, 0.02, 0.1],
    },
    {
      id: 'wiring-loom', cat: 'electrical',
      en: { name: 'Engine wiring loom', summary: 'The sheathed harness feeding every sensor and actuator.',
        does: 'Carries power and signal between the engine control unit and the injectors, coils, cam and crank sensors and the throttle.',
        connects: 'Clipped along the cover and head, plugged into each component and routed to the bulkhead connector.', parts: ['Sheathed harness', 'Injector connectors', 'Coil connectors', 'Retaining clips'] },
      bm: { name: 'Tali pinggang wayar enjin', summary: 'Rangkaian bersarung yang menyuap setiap penderia dan penggerak.',
        does: 'Membawa kuasa dan isyarat antara unit kawalan enjin dengan penyuntik, gegelung, penderia sesondol dan engkol serta pendikit.',
        connects: 'Diklip di sepanjang penutup dan kepala, dipalamkan ke setiap komponen dan disalurkan ke penyambung sekatan.', parts: ['Rangkaian bersarung', 'Penyambung penyuntik', 'Penyambung gegelung', 'Klip penahan'] },
      offset: [0, 0.3, -0.26],
    },
  ];
  return base.map(c => (over[c.id] ? { ...c, ...over[c.id] } : c));
}

/* ───────────────────────── per-car manifests ───────────────────────── */

export const CARS = {
  r32: {
    id: 'r32', layout: 'vr6',
    brand: 'VOLKSWAGEN', model: { en: 'Golf Mk5 R32', bm: 'Golf Mk5 R32' },
    code: '3.2 VR6', yearLabel: '2006 · MK5 · BUB',
    tagline: { en: 'Inside the engineering.', bm: 'Meneliti kejuruteraannya.' },
    facts: [
      { value: '3.2', unit: { en: 'LITRE', bm: 'LITER' } },
      { value: '6', unit: { en: 'CYLINDERS', bm: 'SILINDER' } },
      { value: '24', unit: { en: 'VALVES', bm: 'INJAP' } },
      { value: '15°', unit: { en: 'BANK ANGLE', bm: 'SUDUT BANK' } },
    ],
    studio: 'r32-studio.html', fourStroke: 'engine-lab.html?car=r32',
    gearbox: 'r32-dsg-lab.html',
    note: {
      en: 'Six cylinders in two closely staggered rows under one cylinder head — the layout that makes a VR6 a VR6.',
      bm: 'Enam silinder dalam dua baris berselang-seli rapat di bawah satu kepala silinder — susunan yang menjadikan VR6 itu VR6.',
    },
    sources: [
      { href: 'https://www.volkspage.net/technik/ssp/ssp/SSP_380.pdf', text: 'Audi / Volkswagen SSP 380 · 3.2 VR6 MPI (BUB)' },
      { href: 'https://www.volkswagen-newsroom.com/en/golf-5-20032008-19480', text: 'Volkswagen · Golf 5 model history' },
    ],
    components: inline4Components().filter(c => !['turbocharger', 'acoustic-cover'].includes(c.id)).map(c => {
      if (c.id === 'intake-manifold') return { ...c,
        en: { ...c.en, name: 'Intake manifold', summary: 'Shares incoming air between the six cylinders.',
          does: 'The long plenum sits across the head and the runners split left and right to reach the two staggered cylinder rows.',
          connects: 'Bolts to the single intake face of the VR6 head; the throttle body sits at one end of the plenum.',
          parts: ['Plenum', 'Six runners', 'Throttle body', 'Gaskets'] },
        bm: { ...c.bm, name: 'Manifold masuk', summary: 'Mengagihkan udara masuk kepada enam silinder.',
          does: 'Plenum panjang merentasi kepala dan salurannya bercabang kiri dan kanan untuk mencapai dua baris silinder berselang-seli.',
          connects: 'Diskru pada satu-satunya muka masuk kepala VR6; badan pendikit berada di satu hujung plenum.',
          parts: ['Plenum', 'Enam saluran', 'Badan pendikit', 'Gasket'] },
        offset: [0, 0.3, 0.12] };
      if (c.id === 'cylinder-head') return { ...c,
        en: { ...c.en, summary: 'One head covering both staggered cylinder rows.',
          does: 'Because the banks are only 15° apart, a single casting covers all six bores and carries both camshafts — the feature that lets a six fit a four-cylinder engine bay.',
          parts: ['Head casting', 'Valve seats and guides', 'Spark plug tubes', 'Both cam journals'] },
        bm: { ...c.bm, summary: 'Satu kepala merangkumi kedua-dua baris silinder berselang-seli.',
          does: 'Kerana kedua-dua bank hanya 15° terpisah, satu tuangan merangkumi kesemua enam gerek dan membawa kedua-dua aci sesondol — ciri yang membolehkan enjin enam silinder muat dalam ruang enjin empat silinder.',
          parts: ['Tuangan kepala', 'Tempat duduk dan pemandu injap', 'Tiub palam pencucuh', 'Kedua-dua jurnal sesondol'] },
        offset: [0, 0.11, 0] };
      if (c.id === 'cylinder-block') return { ...c,
        en: { ...c.en, summary: 'One casting holding six staggered bores.',
          does: 'The bores alternate 12.5 mm either side of the centreline so six cylinders fit in a block barely longer than a four. The crankshaft runs in seven main bearings beneath them.',
          parts: ['Block casting', 'Six bores', 'Main bearing caps', 'Core plugs'] },
        bm: { ...c.bm, summary: 'Satu tuangan memegang enam gerek berselang-seli.',
          does: 'Gereknya berselang 12.5 mm di kiri dan kanan garis tengah supaya enam silinder muat dalam blok yang hampir sepanjang blok empat silinder. Aci engkol berputar dalam tujuh galas utama di bawahnya.',
          parts: ['Tuangan blok', 'Enam gerek', 'Tutup galas utama', 'Palam teras'] },
        offset: [0, 0, 0] };
      if (c.id === 'exhaust-manifold') return { ...c,
        en: { ...c.en, summary: 'Collects the burnt gas from all six cylinders.',
          does: 'Gathers six exhaust ports into the downpipe. The R32 is naturally aspirated, so there is no turbine in this path.',
          parts: ['Six runners', 'Collector', 'Flange and studs'] },
        bm: { ...c.bm, summary: 'Mengumpul gas terbakar daripada keenam-enam silinder.',
          does: 'Menghimpunkan enam liang ekzos ke paip turun. R32 bersedutan asli, jadi tiada turbin dalam laluan ini.',
          parts: ['Enam saluran', 'Pengumpul', 'Bebibir dan stad'] },
        offset: [0, 0.08, -0.4] };
      if (c.id === 'cooling-pack') return { ...c,
        en: { ...c.en, does: 'The radiator sheds the heat the coolant has picked up from the block and head. The oil cooler beside it stabilises oil temperature. Naturally aspirated, so there is no charge cooler.',
          parts: ['Radiator core and tanks', 'Oil cooler', 'Mounting brackets'] },
        bm: { ...c.bm, does: 'Radiator melepaskan haba yang diambil penyejuk dari blok dan kepala. Penyejuk minyak di sebelahnya menstabilkan suhu minyak. Bersedutan asli, jadi tiada penyejuk cas.',
          parts: ['Teras dan tangki radiator', 'Penyejuk minyak', 'Pendakap pemasangan'] },
        offset: [0.46, 0.06, 0.36] };
      return c;
    }),
  },

  bmw: {
    id: 'bmw', layout: 'inline4-n20',
    brand: 'BMW', model: { en: 'X4 F26 xDrive20i', bm: 'X4 F26 xDrive20i' },
    code: 'N20', yearLabel: '2016 · F26 · N20B20',
    tagline: { en: 'Inside the engineering.', bm: 'Meneliti kejuruteraannya.' },
    facts: [
      { value: '2.0', unit: { en: 'LITRE', bm: 'LITER' } },
      { value: '4', unit: { en: 'CYLINDERS', bm: 'SILINDER' } },
      { value: '16', unit: { en: 'VALVES', bm: 'INJAP' } },
      { value: '135', unit: { en: 'kW / 184 PS', bm: 'kW / 184 PS' } },
    ],
    studio: 'x4-studio.html', fourStroke: 'engine-lab.html?car=bmw',
    gearbox: 'bmw-x4-lab.html',
    note: {
      en: 'A twin-scroll turbo four with variable cam timing and variable intake-valve lift. The explorer shows the hardware; the four-stroke lab shows the cycle.',
      bm: 'Enjin empat silinder turbo dwi-skrol dengan pemasaan sesondol boleh ubah dan angkatan injap masuk boleh ubah. Penjelajah menunjukkan perkakasannya; makmal empat lejang menunjukkan kitarannya.',
    },
    sources: [
      { href: 'https://www.press.bmwgroup.com/global/article/attachment/T0169768EN/252711', text: 'BMW · X4 F26 xDrive20i specifications' },
      { href: 'https://bmwrepairguide.com/virtual-library/technical-training/ST1111%20N20%20Engine.pdf', text: 'BMW · N20 engine training' },
    ],
    components: inline4Components({
      'valvetrain': {
        id: 'valvetrain', cat: 'valve', offset: [0, 0.17, 0],
        en: { name: 'Camshafts, VANOS and Valvetronic', summary: 'Opens the valves, and varies both when and how far.',
          does: 'Double VANOS rotates each camshaft relative to the chain drive to shift valve timing. Valvetronic adds an eccentric shaft and intermediate levers that vary intake valve lift, so the throttle does less of the load control.',
          connects: 'Camshafts sit in the head on cam caps; the eccentric shaft runs above the intake camshaft with its own motor.',
          parts: ['Intake camshaft', 'Exhaust camshaft', 'VANOS adjusters', 'Eccentric shaft', 'Intermediate levers'] },
        bm: { name: 'Aci sesondol, VANOS dan Valvetronic', summary: 'Membuka injap, dan mengubah bila serta sejauh mana.',
          does: 'Double VANOS memutarkan setiap aci sesondol berbanding pemacu rantai untuk mengalih pemasaan injap. Valvetronic menambah aci sipi dan tuas perantara yang mengubah angkatan injap masuk, jadi pendikit kurang mengawal beban.',
          connects: 'Aci sesondol duduk dalam kepala di atas tutup sesondol; aci sipi berjalan di atas aci sesondol masuk dengan motornya sendiri.',
          parts: ['Aci sesondol masuk', 'Aci sesondol ekzos', 'Pelaras VANOS', 'Aci sipi', 'Tuas perantara'] },
      },
      'turbocharger': {
        id: 'turbocharger', cat: 'air', offset: [0.08, 0.14, -0.42],
        en: { name: 'Twin-scroll turbocharger', summary: 'Two separate exhaust paths into one turbine.',
          does: 'Cylinders are paired into two scrolls that reach the turbine separately, so the pulses of one cylinder do not interfere with another still finishing its exhaust stroke. Response builds earlier than a single-scroll housing of the same size.',
          connects: 'Bolted to the exhaust manifold outlet, oil-fed from the block, compressor outlet piped to the charge cooler.',
          parts: ['Twin-scroll turbine housing', 'Compressor housing', 'Centre housing', 'Wastegate actuator', 'Oil feed and drain'] },
        bm: { name: 'Pengecas turbo dwi-skrol', summary: 'Dua laluan ekzos berasingan ke satu turbin.',
          does: 'Silinder dipasangkan ke dua skrol yang sampai ke turbin secara berasingan, jadi denyut satu silinder tidak mengganggu silinder lain yang masih menghabiskan lejang ekzosnya. Sambutannya terbina lebih awal berbanding rumah skrol tunggal bersaiz sama.',
          connects: 'Diskru pada muncung manifold ekzos, disuap minyak dari blok, keluaran pemampat berpaip ke penyejuk cas.',
          parts: ['Rumah turbin dwi-skrol', 'Rumah pemampat', 'Rumah tengah', 'Penggerak gerbang buang', 'Suapan dan saliran minyak'] },
      },
    }),
  },

  sharan: {
    id: 'sharan', layout: 'inline4-ea888',
    brand: 'VOLKSWAGEN', model: { en: 'Sharan 7N', bm: 'Sharan 7N' },
    code: '2.0 TSI', yearLabel: '2012 · 7N · EA888',
    tagline: { en: 'Inside the engineering.', bm: 'Meneliti kejuruteraannya.' },
    facts: [
      { value: '2.0', unit: { en: 'LITRE', bm: 'LITER' } },
      { value: '4', unit: { en: 'CYLINDERS', bm: 'SILINDER' } },
      { value: '16', unit: { en: 'VALVES', bm: 'INJAP' } },
      { value: '147', unit: { en: 'kW / 200 PS', bm: 'kW / 200 PS' } },
    ],
    studio: 'sharan-studio.html', fourStroke: 'engine-lab.html?car=sharan',
    gearbox: 'sharan-dsg-lab.html',
    note: {
      en: 'A turbocharged, direct-injection four. The gearbox behind it is shown with a published DQ250 set because this car’s own gearbox code has not been confirmed — check the sticker on the box before ordering anything.',
      bm: 'Enjin empat silinder berturbo dengan suntikan terus. Kotak gear di belakangnya ditunjukkan dengan set DQ250 yang diterbitkan kerana kod kotak gear kereta ini belum disahkan — semak pelekat pada kotak gear sebelum memesan apa-apa.',
    },
    sources: [
      { href: 'https://files.samantaz.fr/useful_knowledge/car_repair_manuals/VW/SSP%20445%20Le%20Sharan%202011.pdf', text: 'Volkswagen SSP 445 · Sharan 2.0 TSI' },
      { href: 'https://www.vaglinks.com/docs/ssp/VWUSA.COM_SSP_401_1.8L_TFSI_Engine_16V.pdf', text: 'Volkswagen SSP 401 · EA888 architecture' },
    ],
    components: inline4Components(),
  },

  gt3: {
    id: 'gt3', layout: 'flat6',
    brand: 'PORSCHE', model: { en: '911 GT3 RS', bm: '911 GT3 RS' },
    code: '992', yearLabel: '992 · 4.0 FLAT-SIX',
    tagline: { en: 'Inside the engineering.', bm: 'Meneliti kejuruteraannya.' },
    /* Only figures carried by the cited Porsche specification sheet are listed.
       Bore and stroke are deliberately absent: not confirmed in our source set. */
    facts: [
      { value: '4.0', unit: { en: 'LITRE', bm: 'LITER' } },
      { value: '6', unit: { en: 'CYLINDERS', bm: 'SILINDER' } },
      { value: '386', unit: { en: 'kW / 525 PS', bm: 'kW / 525 PS' } },
      { value: '465', unit: { en: 'Nm', bm: 'Nm' } },
    ],
    studio: 'gt3-rs-studio.html', fourStroke: null, gearbox: null,
    note: {
      en: 'Naturally aspirated, horizontally opposed, mounted behind the rear axle and driving a seven-speed PDK. There is no four-stroke lab or gearbox study for this car yet, and no PDK simulation is implied here.',
      bm: 'Bersedutan asli, tersusun mendatar bertentangan, dipasang di belakang gandar belakang dan memacu PDK tujuh kelajuan. Belum ada makmal empat lejang atau kajian kotak gear untuk kereta ini, dan tiada simulasi PDK disiratkan di sini.',
    },
    sources: [
      { href: 'https://newsroom.porsche.com/dam/jcr:1d390f77-93c3-49c0-89c7-634f5f02b26a/S22_3515_en.pdf', text: 'Porsche · 911 GT3 RS technical specifications' },
      { href: 'https://newsroom.porsche.com/en/2022/products/porsche-911-gt3-rs-world-premiere-29177.html', text: 'Porsche · 911 GT3 RS world premiere' },
    ],
    components: [
      { id: 'intake-airbox', cat: 'air', offset: [0, 0.34, 0],
        en: { name: 'Induction airbox', summary: 'Feeds both opposed banks from one plenum above the engine.',
          does: 'Air collected behind the rear quarter intakes is steadied in the box and split down individual runners to the six intake ports, three to each side.',
          connects: 'Sits on top of the engine and runs down to both cylinder heads.',
          parts: ['Airbox', 'Six runners', 'Throttle body', 'Seals'] },
        bm: { name: 'Kotak udara induksi', summary: 'Menyuap kedua-dua bank bertentangan dari satu plenum di atas enjin.',
          does: 'Udara yang dikumpul di belakang muncung suku belakang distabilkan dalam kotak dan dipecahkan ke saluran individu ke enam liang masuk, tiga di setiap sisi.',
          connects: 'Terletak di atas enjin dan turun ke kedua-dua kepala silinder.',
          parts: ['Kotak udara', 'Enam saluran', 'Badan pendikit', 'Pengedap'] } },
      { id: 'cam-covers', cat: 'structure', offset: [0, 0, 0.34],
        en: { name: 'Camshaft covers', summary: 'One cover over each opposed bank.',
          does: 'Seals the top of each cylinder head. Because the banks lie flat, these covers face outward to the left and right rather than upward.',
          connects: 'Bolt to the outer face of each cylinder head on moulded gaskets.',
          parts: ['Left cover', 'Right cover', 'Gasket sets'] },
        bm: { name: 'Penutup aci sesondol', summary: 'Satu penutup bagi setiap bank bertentangan.',
          does: 'Mengedap bahagian atas setiap kepala silinder. Kerana banknya terbaring mendatar, penutup ini menghadap ke luar kiri dan kanan, bukan ke atas.',
          connects: 'Diskru pada muka luar setiap kepala silinder dengan gasket acuan.',
          parts: ['Penutup kiri', 'Penutup kanan', 'Set gasket'] } },
      { id: 'valvetrain', cat: 'valve', offset: [0, 0, 0.26],
        en: { name: 'Camshafts and valvetrain', summary: 'Four camshafts — two per bank.',
          does: 'Each head carries its own intake and exhaust camshaft running at half crank speed, opening 24 valves in total.',
          connects: 'Sit in each head on cam caps, driven from the crankshaft at the rear of the engine.',
          parts: ['Four camshafts', 'Cam caps', 'Followers', 'Valve springs'] },
        bm: { name: 'Aci sesondol dan rangkaian injap', summary: 'Empat aci sesondol — dua bagi setiap bank.',
          does: 'Setiap kepala membawa aci sesondol masuk dan ekzosnya sendiri yang berputar pada separuh kelajuan engkol, membuka 24 injap kesemuanya.',
          connects: 'Duduk dalam setiap kepala di atas tutup sesondol, dipacu dari aci engkol di belakang enjin.',
          parts: ['Empat aci sesondol', 'Tutup sesondol', 'Pengikut', 'Spring injap'] } },
      { id: 'cylinder-heads', cat: 'structure', offset: [0, 0, 0.19],
        en: { name: 'Cylinder heads', summary: 'One head per bank of three.',
          does: 'Forms the combustion chambers and carries the ports, valve seats and plugs for its three cylinders.',
          connects: 'Bolt onto the outer ends of each cylinder bank; the manifolds meet their inner and outer faces.',
          parts: ['Two head castings', 'Valve seats and guides', 'Spark plug tubes'] },
        bm: { name: 'Kepala silinder', summary: 'Satu kepala bagi setiap bank tiga silinder.',
          does: 'Membentuk kebuk pembakaran serta membawa liang, tempat duduk injap dan palam untuk tiga silindernya.',
          connects: 'Diskru pada hujung luar setiap bank silinder; manifold bertemu muka dalam dan luarnya.',
          parts: ['Dua tuangan kepala', 'Tempat duduk dan pemandu injap', 'Tiub palam pencucuh'] } },
      { id: 'cylinder-banks', cat: 'structure', offset: [0, 0, 0.11],
        en: { name: 'Cylinder banks', summary: 'Three bores lying flat on each side.',
          does: 'The opposed layout puts the pistons’ mass low and close to the crank axis, which is why the engine can sit behind the rear axle without raising the car’s centre of gravity.',
          connects: 'Bolt to each side of the crankcase; heads cap their outer ends.',
          parts: ['Six cylinders', 'Liners', 'Cooling fins and jackets'] },
        bm: { name: 'Bank silinder', summary: 'Tiga gerek terbaring mendatar di setiap sisi.',
          does: 'Susunan bertentangan meletakkan jisim omboh rendah dan dekat dengan paksi engkol, sebab itulah enjin boleh duduk di belakang gandar belakang tanpa menaikkan pusat graviti kereta.',
          connects: 'Diskru pada setiap sisi kotak engkol; kepala menutup hujung luarnya.',
          parts: ['Enam silinder', 'Pelapik', 'Sirip dan jaket penyejukan'] } },
      { id: 'crankcase', cat: 'structure', offset: [0, 0, 0],
        en: { name: 'Crankcase', summary: 'The split central casting both banks bolt to.',
          does: 'Carries the crankshaft main bearings along its centreline and takes the load of both opposed banks.',
          connects: 'Banks to each side, oil housing below, transaxle on its forward face.',
          parts: ['Case halves', 'Main bearing saddles', 'Through-bolts'] },
        bm: { name: 'Kotak engkol', summary: 'Tuangan tengah terbelah tempat kedua-dua bank diskru.',
          does: 'Membawa galas utama aci engkol di sepanjang garis tengahnya dan menanggung beban kedua-dua bank bertentangan.',
          connects: 'Bank di setiap sisi, rumah minyak di bawah, transaxle pada muka hadapannya.',
          parts: ['Belahan kotak', 'Pelana galas utama', 'Bolt tembus'] } },
      { id: 'crank-assembly', cat: 'rotating', offset: [0, -0.05, -0.3],
        en: { name: 'Crankshaft, rods and pistons', summary: 'Turns opposed combustion into rotation.',
          does: 'Pistons on opposite sides work against shared crank throws, so their inertia largely cancels — one reason a flat-six runs as smoothly as it does to 9,000 rpm.',
          connects: 'Runs in the crankcase main bearings; the PDK transaxle takes the output.',
          parts: ['Crankshaft', 'Six connecting rods', 'Pistons and rings', 'Bearing shells'] },
        bm: { name: 'Aci engkol, rod dan omboh', summary: 'Menukar pembakaran bertentangan kepada putaran.',
          does: 'Omboh di sisi bertentangan bekerja pada engkol yang dikongsi, jadi inersianya sebahagian besar saling membatalkan — satu sebab enjin flat-six berputar selancar itu sehingga 9,000 rpm.',
          connects: 'Berputar dalam galas utama kotak engkol; transaxle PDK mengambil keluarannya.',
          parts: ['Aci engkol', 'Enam rod penyambung', 'Omboh dan gelang', 'Kulit galas'] } },
      { id: 'oil-housing', cat: 'structure', offset: [0, -0.32, 0],
        en: { name: 'Oil housing', summary: 'The lower casting of the lubrication system.',
          does: 'Closes the bottom of the crankcase and carries the pump and gallery feeds. A flat engine cannot rely on a deep sump, so scavenge and supply are handled by pumps rather than gravity alone.',
          connects: 'Bolts under the crankcase; lines run to the coolers and the oil tank.',
          parts: ['Housing', 'Pump drive', 'Drain plug', 'Gallery unions'] },
        bm: { name: 'Rumah minyak', summary: 'Tuangan bawah bagi sistem pelinciran.',
          does: 'Menutup bahagian bawah kotak engkol serta membawa pam dan suapan laluan. Enjin mendatar tidak boleh bergantung pada sampan dalam, jadi sedutan dan bekalan dikendalikan oleh pam, bukan graviti semata-mata.',
          connects: 'Diskru di bawah kotak engkol; paip menuju ke penyejuk dan tangki minyak.',
          parts: ['Rumah', 'Pemacu pam', 'Palam buang', 'Sambungan laluan'] } },
      { id: 'exhaust-manifold', cat: 'air', offset: [0, -0.1, -0.4],
        en: { name: 'Exhaust manifolds', summary: 'One collector per bank.',
          does: 'Gathers three exhaust ports on each side into a collector. Naturally aspirated, so there is no turbine in this path.',
          connects: 'Bolts to the exhaust face of each head and runs rearward to the silencers.',
          parts: ['Six runners', 'Two collectors', 'Flanges and studs'] },
        bm: { name: 'Manifold ekzos', summary: 'Satu pengumpul bagi setiap bank.',
          does: 'Menghimpunkan tiga liang ekzos di setiap sisi ke satu pengumpul. Bersedutan asli, jadi tiada turbin dalam laluan ini.',
          connects: 'Diskru pada muka ekzos setiap kepala dan menuju ke belakang ke peredam.',
          parts: ['Enam saluran', 'Dua pengumpul', 'Bebibir dan stad'] } },
      { id: 'cooling-pack', cat: 'cooling', offset: [0.5, 0.06, 0.2],
        en: { name: 'Cooling pack', summary: 'Vehicle-mounted radiators and oil cooler, not part of the engine.',
          does: 'A rear-engined car cannot put one radiator in front of its engine, so coolant is piped the length of the car to exchangers in the nose and flanks. The oil cooler stabilises oil temperature under sustained load.',
          connects: 'Carried on the body structure and joined to the engine only by long coolant lines.',
          parts: ['Radiator cores and tanks', 'Oil cooler', 'Mounting brackets'] },
        bm: { name: 'Pek penyejukan', summary: 'Radiator dan penyejuk minyak pada kenderaan, bukan sebahagian enjin.',
          does: 'Kereta berenjin belakang tidak boleh meletakkan satu radiator di hadapan enjinnya, jadi penyejuk dipaipkan sepanjang kereta ke penukar haba di hidung dan rusuk. Penyejuk minyak menstabilkan suhu minyak di bawah beban berterusan.',
          connects: 'Dipikul pada struktur badan dan hanya disambung ke enjin oleh paip penyejuk panjang.',
          parts: ['Teras dan tangki radiator', 'Penyejuk minyak', 'Pendakap pemasangan'] } },
      { id: 'coolant-hoses', cat: 'cooling', offset: [0.3, 0.04, 0.22],
        en: { name: 'Coolant lines', summary: 'The flexible run between engine and exchangers.',
          does: 'Carries hot coolant away from the heads and cooled coolant back, absorbing engine movement on its mounts.',
          connects: 'Clamped to the thermostat housing and the hard lines running forward.',
          parts: ['Upper lines', 'Lower lines', 'Clamps and unions'] },
        bm: { name: 'Paip penyejuk', summary: 'Laluan fleksibel antara enjin dan penukar haba.',
          does: 'Membawa penyejuk panas keluar dari kepala dan penyejuk sejuk kembali, sambil menyerap pergerakan enjin pada dudukannya.',
          connects: 'Diapit pada rumah termostat dan paip keras yang menuju ke hadapan.',
          parts: ['Paip atas', 'Paip bawah', 'Pengapit dan sambungan'] } },
      { id: 'belt-drive', cat: 'ancillary', offset: [-0.4, 0.04, 0],
        en: { name: 'Accessory belt drive', summary: 'Takes power off the crank for the ancillaries.',
          does: 'A ribbed belt from the crank pulley turns the alternator and the air-conditioning compressor under a sprung tensioner.',
          connects: 'Wraps the crank pulley and each accessory pulley at the belt end of the engine.',
          parts: ['Ribbed belt', 'Crank pulley', 'Alternator', 'Tensioner'] },
        bm: { name: 'Pemacu tali sawat', summary: 'Mengambil kuasa dari engkol untuk kelengkapan.',
          does: 'Tali sawat berusuk dari takal engkol memutarkan alternator dan pemampat penyaman udara di bawah penegang berspring.',
          connects: 'Melilit takal engkol dan setiap takal kelengkapan di hujung tali sawat enjin.',
          parts: ['Tali sawat berusuk', 'Takal engkol', 'Alternator', 'Penegang'] } },
      { id: 'wiring-loom', cat: 'electrical', offset: [0, 0.3, 0.2],
        en: { name: 'Engine wiring loom', summary: 'The sheathed harness feeding every sensor and actuator.',
          does: 'Carries power and signal between the control units and the injectors, coils, cam and crank sensors.',
          connects: 'Clipped along the airbox and heads and routed forward to the body connectors.',
          parts: ['Sheathed harness', 'Injector connectors', 'Coil connectors', 'Retaining clips'] },
        bm: { name: 'Tali pinggang wayar enjin', summary: 'Rangkaian bersarung yang menyuap setiap penderia dan penggerak.',
          does: 'Membawa kuasa dan isyarat antara unit kawalan dengan penyuntik, gegelung, penderia sesondol dan engkol.',
          connects: 'Diklip di sepanjang kotak udara dan kepala serta disalurkan ke hadapan ke penyambung badan.',
          parts: ['Rangkaian bersarung', 'Penyambung penyuntik', 'Penyambung gegelung', 'Klip penahan'] } },
    ],
  },
};

export const CAR_ORDER = ['r32', 'bmw', 'sharan', 'gt3'];

/** Step-by-step teaching order. Ids absent from a car are skipped at runtime. */
export const STEP_ORDER = [
  'acoustic-cover', 'cam-cover', 'cam-covers', 'valvetrain', 'cylinder-head', 'cylinder-heads',
  'head-gasket', 'cylinder-banks', 'cylinder-block', 'crankcase', 'crank-assembly',
  'oil-sump', 'oil-housing', 'timing-case', 'intake-manifold', 'intake-airbox',
  'exhaust-manifold', 'turbocharger', 'cooling-pack', 'coolant-hoses', 'belt-drive', 'wiring-loom',
];

/** Semantic component count — not triangles, meshes or engineering part totals. */
export function componentCount(car) { return CARS[car].components.length; }
